"""FTC complaint package generator."""
from __future__ import annotations

import datetime as dt
import logging
import sqlite3
from pathlib import Path
from typing import Any

from sundo.config import FTC_DIR, FTC_PAYMENT_THRESHOLD, SQLITE_PATH

logger = logging.getLogger(__name__)


def _query_violations() -> list[dict[str, Any]]:
    try:
        conn = sqlite3.connect(str(SQLITE_PATH))
        conn.row_factory = sqlite3.Row
        cur = conn.execute(
            "SELECT * FROM ftc_violations WHERE status = 'candidate' AND amount >= ?",
            (FTC_PAYMENT_THRESHOLD,),
        )
        rows = [dict(r) for r in cur.fetchall()]
        conn.close()
        return rows
    except Exception as exc:
        logger.warning("Could not query FTC violations: %s", exc)
        return []


def _format_complaint(violation: dict[str, Any]) -> str:
    handle = violation.get("handle", "unknown")
    amount = violation.get("amount", 0.0) or 0.0
    nature = violation.get("nature", "undisclosed sponsorship / paid influence")
    post_url = violation.get("post_url", "")
    payment_evidence = violation.get("payment_evidence", "")
    date = dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%d")
    return (
        f"# FTC Complaint Package — {handle}\n\n"
        f"**Date:** {date}  \n"
        f"**Complaint ID:** complaint-{handle}-{date}\n\n"
        "## Complainant\n\n"
        "_(Leave blank for manual entry)_\n\n"
        "## Respondent\n\n"
        f"- **Handle:** {handle}\n"
        f"- **Platform:** {violation.get('platform', 'unknown')}\n\n"
        "## Nature of Violation\n\n"
        f"{nature}\n\n"
        "## Evidence A — Public Post\n\n"
        f"{post_url or '_No URL recorded._'}\n\n"
        "## Evidence B — Payment / Compensation\n\n"
        f"{payment_evidence or '_No payment evidence recorded._'}\n\n"
        "## FTC Submission\n\n"
        "Submit via: https://reportfraud.ftc.gov/\n\n"
        "---\n\n"
        "_Generated by Sundo Pi OSINT platform._\n"
    )


def generate_ftc_packages() -> list[Path]:
    """Generate FTC complaint packages for all candidate violations above threshold."""
    FTC_DIR.mkdir(parents=True, exist_ok=True)
    violations = _query_violations()
    paths: list[Path] = []
    today = dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%d")
    for v in violations:
        handle = v.get("handle", "unknown")
        out_path = FTC_DIR / f"complaint-{handle}-{today}.md"
        out_path.write_text(_format_complaint(v), encoding="utf-8")
        paths.append(out_path)
        logger.info("FTC package written: %s", out_path)
    if not violations:
        logger.info("No FTC violations above threshold.")
    return paths


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s: %(message)s")
    generate_ftc_packages()
